Feature/generic repository
kenshi-takahashi/OnlineShop pull request #5
Opened 2024-06-19 08:59 UTC by kenshi-takahashi

Add generic repository and example for other repositories

2024-06-19 09:17 UTC, kenshi-takahashi commented on OnlineShop.DAL/Repositories/CategoryRepository.cs
For example

2024-06-19 09:17 UTC, kenshi-takahashi commented on OnlineShop.DAL/Interfaces/ICategoryRepository.cs
For example

2024-06-19 10:58 UTC, Elizaveta564 requested changes

2024-06-19 10:58 UTC, Elizaveta564 commented on OnlineShop.DAL/Repositories/GenericRepository.cs
> +public class GenericRepository<T> where T : class
need to create IGenericRepository interface

2024-06-19 10:58 UTC, Elizaveta564 commented on OnlineShop.DAL/Repositories/GenericRepository.cs
> +    }
use AsNoTracking() for GET methods

2024-06-19 10:58 UTC, Elizaveta564 commented on OnlineShop.DAL/Repositories/GenericRepository.cs
> +        }
all checks should be in services and not in repositories

2024-06-21 16:00 UTC, Elizaveta564 approved these changes

2024-06-21 16:00 UTC, Elizaveta564 commented on OnlineShop.DAL/Repositories/GenericRepository.cs
> +        return await _context.Set<T>().FindAsync(id);
use AsNoTracking()

2024-06-21 16:06 UTC, kenshi-takahashi commented on OnlineShop.DAL/Repositories/GenericRepository.cs
> +        return await _context.Set<T>().FindAsync(id);
it is impossible to use AsNoTracking() here
![image](https://github.com/kenshi-takahashi/OnlineShop/assets/102070938/059a2507-1b42-4092-81e8-be47f3d2ae6f)

2024-06-21 19:25 UTC, merged